CREATE OR REPLACE TRIGGER TGR_TB_CLASS_UPDATE 
AFTER UPDATE OF ID ON TB_CLASS
FOR EACH ROW
BEGIN
  IF :OLD.ID<>:NEW.ID THEN
    UPDATE TB_STUDENT SET CLASS_ID=:NEW.ID WHERE CLASS_ID=:OLD.ID;
  END IF;
END;